### PR TITLE
Fixes examples to reflect changes in v2

### LINKED ISSUE #15: Wrong Documentation
Hi, I've been using your module for a while and all worked ok.

I saw you made breaking changes and when tried to apply the changes I realize your documentation is a mix between the old way and the new one. 

I guess now we have to use ```on("error", fn)``` instead of ```onError(fn)```, and after ```this.$sse.create``` we have to use ```await sse.connect```, and later ```sse.disconnect```.

Am I right? 

Your examples are all old, can you please update the documentation?

Regards.

### PR DESCRIPTION
**Pull request by tgrk**
Hey :wave:  I just managed to make SSE working after breaking changes in v2. This PR consists of only adjusted examples, but it might be helpful for new users. 

Thanks for this handy library :muscle: 

Cheers,
Martin

Fixes #15

### CODE REVIEW

**Comment by tserkov** [comment]
Thanks @tgrk for doing this, I'm a terrible procrastinator!

**Comment by tgrk** [comment]
@tserkov Haha, I feel you. :smile:  Happy to help.

**Comment by gwh-cpnet** [comment]
But the `subscribe` method is removed too.

**Comment by paolodina** [comment]
@gwh-cpnet yes, `subscribe` and `unsubscribe` are gone.

With v2 you should be able to use `on` and `off`.

Reference: https://github.com/tserkov/vue-sse/commit/e2d293e090d582d8b305389c09fdb9dcfb5e0cdb#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R56

**Pull request merged**
